name: SauroLab
channels:
  - defaults
dependencies:
  - appnope=0.1.2=py38hecd8cb5_1001
  - argon2-cffi=20.1.0=py38h9ed2024_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.0.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py38h9ed2024_1003
  - ca-certificates=2021.7.5=hecd8cb5_1
  - certifi=2021.5.30=py38hecd8cb5_0
  - cffi=1.14.6=py38h2125817_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=3.4.7=py38h2fd3fbb_0
  - debugpy=1.4.1=py38h23ab428_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - idna=3.2=pyhd3eb1b0_0
  - imagesize=1.2.0=pyhd3eb1b0_0
  - importlib-metadata=3.10.0=py38hecd8cb5_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - intel-openmp=2021.3.0=hecd8cb5_3375
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.0=py38hecd8cb5_1
  - jinja2=3.0.1=pyhd3eb1b0_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter_client=7.0.1=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py38hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - libsodium=1.0.18=h1de35cc_0
  - markupsafe=2.0.1=py38h9ed2024_0
  - mistune=0.8.4=py38h1de35cc_1001
  - mkl=2021.3.0=hecd8cb5_517
  - mkl-service=2.4.0=py38h9ed2024_0
  - mkl_fft=1.3.0=py38h4a7008c_2
  - mkl_random=1.2.2=py38hb2f4e1b_0
  - nb_conda=2.2.1=py38_1
  - nb_conda_kernels=2.3.1=py38hecd8cb5_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py38hecd8cb5_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.2=h0a44026_1
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.3=py38hecd8cb5_0
  - openssl=1.1.1l=h9ed2024_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandocfilters=1.4.3=py38hecd8cb5_1
  - parso=0.8.2=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.0.1=py38hecd8cb5_0
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.20=py_2
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyrsistent=0.17.3=py38haf1e3a3_0
  - pysocks=1.7.1=py38_1
  - python=3.8.11=h88f2d9e_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pyzmq=22.2.1=py38h23ab428_1
  - readline=8.1=h9ed2024_0
  - requests=2.26.0=pyhd3eb1b0_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py38hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_0
  - snowballstemmer=2.1.0=pyhd3eb1b0_0
  - sphinx=4.0.2=pyhd3eb1b0_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - sqlite=3.36.0=hce871da_0
  - terminado=0.9.4=py38hecd8cb5_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.10=hb0a8c7a_0
  - tornado=6.1=py38h9ed2024_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h1de35cc_0
  - zeromq=4.3.4=h23ab428_0
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - antimony==2.12.0
    - appdirs==1.4.4
    - cycler==0.10.0
    - docutils==0.16
    - entrypoints==0.3
    - iniconfig==1.1.1
    - ipykernel==6.3.1
    - ipython==7.27.0
    - jupyter-client==7.0.2
    - kiwisolver==1.3.2
    - libroadrunner==2.0.5
    - matplotlib==3.4.3
    - matplotlib-inline==0.1.3
    - numpy==1.19.3
    - pandas==1.3.2
    - phrasedml==1.1.1
    - pillow==8.3.2
    - plotly==5.3.1
    - pluggy==1.0.0
    - prompt-toolkit==3.0.20
    - py==1.10.0
    - pytest==6.2.5
    - python-libcombine==0.2.13
    - python-libnuml==1.1.4
    - python-libsbml==5.19.0
    - python-libsedml==2.0.26
    - rrplugins==2.0.4
    - sbml2matlab==1.2.0
    - scipy==1.7.1
    - sphinx-rtd-theme==0.5.2
    - tellurium==2.2.0
    - tenacity==8.0.1
    - toml==0.10.2
    - traitlets==5.1.0
prefix: /Users/evan/opt/anaconda3/envs/SauroLab
